name: addaproject
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^3.0.0
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.0.0
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profilebackground.png
    - assets/generalbackground.png
    - assets/welcomebackground.png
    - assets/logoadda.png
    - assets/blackwave.png
    - assets/blackwavetwo.png
    - assets/personalizeprofile.png
    - assets/astronautinha.png
    - assets/torredesinal.png
    - assets/voltarbtn.png
    - assets/target.png
    - assets/setinha.png
    - assets/lanita.png
    - assets/bglanita.png
    - assets/iconcompartilharlink.png
    - assets/transparenttarget.png
    - assets/billie.png
    - assets/bgbillie.png

  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-Regular.ttf
        - asset: assets/fonts/Amaranth-Italic.ttf
        - asset: assets/fonts/Amaranth-Bold.ttf
        - asset: assets/fonts/Amaranth-BoldItalic.ttf
        - asset: assets/fonts/Inter.ttf