name: addaproject
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/registerbackground.png
    - assets/logoadda.png
    - assets/blackwave.png
    - assets/astronautinha.png
    - assets/torredesinal.png

  fonts:
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-Regular.ttf
        - asset: assets/fonts/Amaranth-Italic.ttf
        - asset: assets/fonts/Amaranth-Bold.ttf
        - asset: assets/fonts/Amaranth-BoldItalic.ttf
        - asset: assets/fonts/Inter.ttf
